### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by msmsubair** [rusitschka/openwrt-mikrotik#3]
Hi
I was building docker on ubuntu 18 and get the following error.

# configuration written to .config
#
+ exec ./docker-scripts/firmware.sh
/entrypoint.sh: line 8: /root/openwrt/docker-scripts/firmware.sh: No such file or directory

can you help ?

**Comment by rusitschka** [comment]
This should be fixed by 39a7258317eabf512d780876a3c6c63c792225e6 however I currently cannot test because the patch currently doesn't apply against master.
